//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElectronRepository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.Orders = new HashSet<Order>();
            this.Stocks = new HashSet<Stock>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<double> price { get; set; }
        public string brand { get; set; }
        public Nullable<int> rating { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string description { get; set; }
        public Nullable<int> category_id { get; set; }
        public string image { get; set; }
        public string fileName { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<Stock> Stocks { get; set; }
    }
}
